### ISSUE TITLE
Set execution effort weights to current defaults

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/service-account#108]
## Summary 

Currently the defaults for the execution effort weights are read from the code instead of from the state.

This produces the following logs on the execution node: 
```
{"level":"info","node_role":"execution","node_id":"160241f88cbfaa0f361cf64adb0a1c9fc19dec1daf4b96550cd67b7a9fb26cd9","error":"[Error Code: 1112] could not get execution parameter from the state (address: e467b9dd11fa00df path: storage/executionEffortWeights)","time":"2022-04-06T23:24:26Z","message":"could not set execution weights. Using defaults"}
```

To avoid this log the same defaults should be set on the service account.

The transaction template needed for setting these parameters was added with this [PR](https://github.com/onflow/flow-core-contracts/pull/284)

The relevant code can be found here:
- https://github.com/onflow/flow-go/blob/1df43de85c5b75618511a8fe99e9998ab2e4cd59/fvm/meter/weighted/meter.go#L20
- https://github.com/onflow/flow-go/blob/1df43de85c5b75618511a8fe99e9998ab2e4cd59/fvm/fvm.go#L105
- https://github.com/onflow/flow-go/blob/1df43de85c5b75618511a8fe99e9998ab2e4cd59/fvm/transactionEnv.go#L113

## Transactions to execute

- **TX**: https://github.com/onflow/flow-core-contracts/blob/master/transactions/FlowServiceAccount/set_execution_effort_weights.cdc
- **authorizer**: The transaction should be sent with the service account
- **parameters**:

```json
 [
   {
     "type": "Dictionary",
     "value": [
       {
         "key": { "type": "UInt64", "value": "1001" },
         "value": { "type": "UInt64", "value": "65536" }
       },
       {
         "key": { "type": "UInt64", "value": "1002" },
         "value": { "type": "UInt64", "value": "65536" }
       },
       {
         "key": { "type": "UInt64", "value": "1003" },
         "value": { "type": "UInt64", "value": "65536" }
       }
     ]
   }
]
```

The sets the execution weights to:
- ComputationKindLoop = 1
- ComputationKindStatement = 1 
- ComputationKindFunctionInvocation = 1

**Comment by janezpodhostnik** [comment]
Testnet: `e36334d0f2461af402c68fe61cfb405703ed6aea0b1b6c5f5f233ea661dd887b`

**Comment by Kay-Zee** [comment]
this is sent: 

https://github.com/onflow/service-account/commit/1ecce34247ffacb074c292a8ba304cae8923a047

Mainnet: `546574b9c27f2fed98244cd99e982f468f331b41933ab1003600da7238635617`
