### ISSUE TITLE
Enable new execution effort metering and fees for execution effort

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/service-account#110]
# Summary

FLIP [Variable Transaction Fees - Execution Effort I.](https://github.com/onflow/flow/blob/master/flips/20220111-execution-effort.md)
describes how the execution effort weights and the fee factors should be set.

Two transactions need to be run. The first sets the execution effort weights to the correct numbers. The second reduces the inclusion cost and sets the execution costs to non-zero. There can be a pause between the transactions. During the pause, the metering will be changed, but the fees will still be static.

⚠️ The change to execution effort metering also means that some transactions that would previously pass, will now hit the computation limit.

## Transactions

Preferably in this order.

- Tx 1: [set_execution_effort_weights](https://github.com/onflow/flow-core-contracts/blob/master/transactions/FlowServiceAccount/set_execution_effort_weights.cdc)
    - authorizer: service account
    - args:
    ```json
        [
      {
        "type": "Dictionary",
        "value": [
          {
            "key": { "type": "UInt64", "value": "1001" },
            "value": { "type": "UInt64", "value": "1569" }
          },
          {
            "key": { "type": "UInt64", "value": "1002" },
            "value": { "type": "UInt64", "value": "1569" }
          },
          {
            "key": { "type": "UInt64", "value": "1003" },
            "value": { "type": "UInt64", "value": "1569" }
          },
          {
            "key": { "type": "UInt64", "value": "2006" },
            "value": { "type": "UInt64", "value": "2837670" }
          },
          {
            "key": { "type": "UInt64", "value": "2020" },
            "value": { "type": "UInt64", "value": "808" }
          },
          {
            "key": { "type": "UInt64", "value": "2026" },
            "value": { "type": "UInt64", "value": "765" }
          }
        ]
      }
    ]
    ```
- Tx 2: [set_tx_fee_parameters](https://github.com/onflow/flow-core-contracts/blob/master/transactions/FlowServiceAccount/set_tx_fee_parameters.cdc)
    - authorizer: service account
    - args:
        - surgeFactor: 1.0 
        - inclusionEffortCost: 0.000001 
        - executionEffortCost: 4.99049905
    

## Validation

In case the parameters need to be checked that they are set to the correct values

- Script 1: [get_execution_effort_weights](https://github.com/onflow/flow-core-contracts/blob/master/transactions/FlowServiceAccount/scripts/get_execution_effort_weights.cdc) (will not work before https://github.com/onflow/service-account/issues/109)
- Script 2: [get_tx_fee_parameters.cdc](https://github.com/onflow/flow-core-contracts/blob/master/transactions/FlowServiceAccount/scripts/get_tx_fee_parameters.cdc)

## In case of problems: Restore previous metering and fees

In case we want to undo this change and restore previous metering and fees.

- Tx 1: [set_tx_fee_parameters](https://github.com/onflow/flow-core-contracts/blob/master/transactions/FlowServiceAccount/set_tx_fee_parameters.cdc)
    - authorizer: flow id table staking (service account on canary)
    - args:
        - surgeFactor: 1.0 
        - inclusionEffortCost: 0.00001 
        - executionEffortCost: 0.0
- Tx 2: [set_execution_effort_weights](https://github.com/onflow/flow-core-contracts/blob/master/transactions/FlowServiceAccount/set_execution_effort_weights.cdc)
    - authorizer: service account
    - args:
    ```json
    [
      {
        "type": "Dictionary",
        "value": [
          {
            "key": { "type": "UInt64", "value": "1001" },
            "value": { "type": "UInt64", "value": "65536" }
          },
          {
            "key": { "type": "UInt64", "value": "1002" },
            "value": { "type": "UInt64", "value": "65536" }
          },
          {
            "key": { "type": "UInt64", "value": "1003" },
            "value": { "type": "UInt64", "value": "65536" }
          }
        ]
      }
    ]
    ```

**Comment by janezpodhostnik** [comment]
canary:
- Tx 1: `7c178076e2ffd274e851252dbd79400e253943d21759942c6b3b48bd20b4a8e5`
- Tx 2: `fe5ed264618148a0229fe8eebe420a0efc5164136d4083f76a24975052e8d747`

**Comment by Darrenic17** [comment]
Connect with our  team representatives to help resolve your issue and troubleshooting .
Connect here: direct.lc.chat/14158209/

Hours of Operation
24/7 (Ready to fix issues)
