### ISSUE TITLE
Turn on permissionless contract deployment on maminnet

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/service-account#142]
# Summary

Permissionless contract deployment should be turned on on date ⚠️ TODO ⚠️ on mainnet. More details about the various settings around this can be found here: https://www.notion.so/dapperlabs/Enable-Permissionless-Contract-Deployment-On-mainnet-3a9ff010423444c0975ed6052e028968

# Transaction to execute

- **code**:
    ```cadence
    transaction(restricted: Bool) {
	    prepare(signer: AuthAccount) {
		    signer.load<Bool>(from: /storage/isContractDeploymentRestricted)
		    signer.save(restricted, to: /storage/isContractDeploymentRestricted)
	    }
    }
    ```
- **parameter**: `false` (as in "the deployment should not be restricted")
- **signer**: service account (doing this on any other account will succeed, but will have no effect) 

# Contingency

In case of problems related to people deploying contracts this action can be undone by sending the same transaction, but setting the **parameter** to `true`

**Comment by janezpodhostnik** [comment]
Canary TX: `06a1c8bce5b3e35787267d140f7f1f6d61cd85f7d0aaf6e84c31bc8f2200db29`
Testnet TX: `e36334d0f2461af402c68fe61cfb405703ed6aea0b1b6c5f5f233ea661dd887b`

**Comment by pgebheim** [comment]
Done
