### ISSUE TITLE
Deploy ABI Encoding Decoding

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/service-account#284]
Deploy a limited version of the EVM contract to service account. The limited version of the EVM contract contains only the ABI encoding and decoding.

The contract can be fount here: https://github.com/onflow/flow-go/blob/master/fvm/evm/stdlib/abiOnlyContract.cdc

This contract can only be deployed after the HCU on Wednesday 7.2.2024.

**Comment by vishalchangrani** [comment]
@janezpodhostnik what account should deploy this contract?

**Comment by janezpodhostnik** [comment]
The service account
