### ISSUE TITLE
Add excluded address to Dependency Audit

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/service-account#296]
We should add `MigrationContractStaging` address to the exclusion list for the dependency check:

- Transaction code: https://github.com/onflow/contract-updater/blob/db30f01/transactions/dependency-audit/admin/add_excluded_addresses.cdc
	- The import should be: `import DependencyAudit from 0xe467b9dd11fa00df`
- The signer Is the service account
- The arguments are: 
```
[
    {
        "type": "Array",
        "value": [
            {
                "type": "Address",
                "value": "0x56100d46aa9b0212"
            }
        ]
    }
]
```

This is the MigrationContractStaging address 
https://contractbrowser.com/A.56100d46aa9b0212.MigrationContractStaging

**Comment by janezpodhostnik** [comment]
@joshuahannan should we stage the contract instead?

**Comment by sisyphusSmiling** [comment]
I don't see a problem with staging the contract. It's been [staged on Testnet](https://f.dnz.dev/0x2ceae959ed1a7e7a/0x2ceae959ed1a7e7a_MigrationContractStaging) for some time and [seems to be migrating](https://github.com/onflow/cadence/blob/master/migrations_data/staged-contracts-report-2024-06-12T13-03-00Z-testnet.md?plain=1#L361) just fine

**Comment by janezpodhostnik** [comment]
Alright lets not do this transaction then!

**Comment by sisyphusSmiling** [comment]
FYI I staged MigrationContractStaging on Mainnet as well in transaction [29c21e4b2217edabb4fb7d218ba791420fcdbbff9e0495005291dfdf18ea4150](https://www.flowdiver.io/tx/29c21e4b2217edabb4fb7d218ba791420fcdbbff9e0495005291dfdf18ea4150)
